name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.108
    - name: List files for debugging
      run: ls -R
    - name: Check file permissions
      run: ls -l /home/runner/work/TEStudio/TEStudio/腾易工作室前端

    - name: Restore dependencies
      run: dotnet restore ./TEStudio/腾易工作室前端/滕易工作室前端.sln

      




