name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Verify current directory
      run: pwd

    - name: List files in repository
      run: ls -R

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.108
    
    - name: Restore dependencies
      run: dotnet restore "./腾易工作室前端/滕易工作室前端.sln"

      




